spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1313
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB

jwt:
  expiration_time: 86400000
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

google:
  maps:
    api-key: AIzaSyDctBzKQ0wsNg94opERP27ceJ9kD63I6QU

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: cbjunbucket
    credentials:
      accessKey: AKIAQ3EGU3FH4IDGBCWM
      secretKey: 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

