spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration_time: 86400000
  secret_key: asdf

